name: opentrivia
description: A new Flutter project.

version: 1.0.2+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.4.0
  http: ^0.12.0+2
  flutter_custom_clippers: ^0.1.6
  html_unescape: ^1.0.1+2
  auto_size_text: ^2.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300